apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ml5m51pjr-go 
  janus-idp.io/tekton: ml5m51pjr-go
  backstage.io/kubernetes-id: ml5m51pjr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ml5m51pjr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  