apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ml5m51pjr-go
  janus-idp.io/tekton: ml5m51pjr-go
  backstage.io/kubernetes-id: ml5m51pjr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ml5m51pjr-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
